[package]
name = "tceq-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["string"] }
csv = "1.3.0"
minreq = "2.11.2"
rusqlite = "0.31.0"
scraper = "0.19.0"
