[package]
name = "tceq-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["string"] }
csv = "1.3.0"
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"
minreq = { version = "2.11.2", features = ["https-rustls"] }
rusqlite = "0.31.0"
